//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NerdDinner.Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.ICommandService")]
    public interface ICommandService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/RegisterUser", ReplyAction="http://tempuri.org/ICommandService/RegisterUserResponse")]
        System.Web.Security.MembershipCreateStatus RegisterUser(NerdDinner.Commands.RegisterUserCommand registerUserCommand);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandService/ChangePassword", ReplyAction="http://tempuri.org/ICommandService/ChangePasswordResponse")]
        bool ChangePassword(NerdDinner.Commands.ChangePasswordCommand changePasswordCommand);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommandServiceChannel : NerdDinner.Services.ICommandService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommandServiceClient : System.ServiceModel.ClientBase<NerdDinner.Services.ICommandService>, NerdDinner.Services.ICommandService {
        
        public CommandServiceClient() {
        }
        
        public CommandServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommandServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommandServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommandServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Web.Security.MembershipCreateStatus RegisterUser(NerdDinner.Commands.RegisterUserCommand registerUserCommand) {
            return base.Channel.RegisterUser(registerUserCommand);
        }
        
        public bool ChangePassword(NerdDinner.Commands.ChangePasswordCommand changePasswordCommand) {
            return base.Channel.ChangePassword(changePasswordCommand);
        }
    }
}
